[build-system]
requires = ["flit_core>=3.12,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pyflowbatt"
version = "0.2.1"
description = "Tools for analysing data from the flow battery lab at Empa"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "batterydf>=0.1.0,<0.2.0",
    "battinfoconverter-backend>=3.3.1",
    "fasteis==0.1.0",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
    "xlsxwriter>=3.2.9",
    "rocrate>=0.9",
    "yadg>=6.2.2,<7.0.0",
    "tomli>=2.0.0; python_version < '3.11'",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.13.2",
    "pre-commit>=4.2.0",
]

[project.scripts]
pyflowbatt = "pyflowbatt.cli:main"
flussli = "pyflowbatt.cli:main"

[tool.uv]
default-groups = ["dev"]

[tool.ruff]
line-length = 100  # Set the maximum line length
lint.select = ["ALL"]
lint.ignore = [
    "N803",
    "N806",
    "N815",
    "PLR2004",
    "TD002",
    "TD003",
    "D203",
    "D213",
    "COM812",
]
fix = true

[tool.ruff.lint.extend-per-file-ignores]
"tests/*.py" = [
    "S101", # asserts allowed in tests
    "PT011", # allow just checking for ValueError without match
]

[tool.mypy]
disable_error_code = ["import-untyped"]
exclude = [
    "test\\.py$", # files end with test.py
    "^test", # files that start with test
]
