[project]
name = "flussli"
dynamic = ["version"]
description = "Tools for analysing data from the flow battery lab at Empa"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "impedance>=1.7.1",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
    "tqdm>=4.67.1",
    "xlsxwriter>=3.2.9",
    "yadg>=6.2.2,<7.0.0",
]

[project.optional-dependencies]
dev = [
    "bumpver>=2025.1131",
    "pytest>=8.4.2",
    "ruff>=0.13.2",
    "pre-commit>=4.2.0",
]

[project.scripts]
flussli = "flussli.cli:main"

[tool.ruff]
line-length = 100  # Set the maximum line length
lint.select = ["ALL"]
lint.ignore = [
    "N803",
    "N806",
    "N815",
    "PLR2004",
    "TD002",
    "TD003",
    "D203",
    "D213",
    "COM812",
]
fix = true

[tool.ruff.lint.extend-per-file-ignores]
"tests/*.py" = [
    "S101", # asserts allowed in tests
    "PT011", # allow just checking for ValueError without match
]

[tool.mypy]
disable_error_code = ["import-untyped"]
exclude = [
    "test\\.py$", # files end with test.py
    "^test", # files that start with test
]

[tool.bumpver]
current_version = "v0.1.0"
version_pattern = "vMAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "Bump version {old_version} -> {new_version}."
tag_message = "Release {new_version}."
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"flussli/version.py" = [
    '__version__ = "{pep440_version}"',
]
